export const iconPaths = {
  alertCircle: "/icons/alert-circle.svg",
  alertTriangle: "/icons/alert-triangle.svg",
  arrowRight: "/icons/arrow-right.svg",
  arrowUpRight: "/icons/arrow-up-right.svg",
  chartGantt: "/icons/chart-gantt.svg",
  check: "/icons/check.svg",
  checkCircle: "/icons/check-circle.svg",
  chevronDown: "/icons/chevron-down.svg",
  chevronRight: "/icons/chevron-right.svg",
  cog: "/icons/cog.svg",
  creditCard: "/icons/credit-card.svg",
  eye: "/icons/eye.svg",
  filter: "/icons/filter.svg",
  info: "/icons/info.svg",
  iosBatteryFull: "/icons/ios-battery-full.svg",
  iosSignal: "/icons/ios-signal.svg",
  iosWifiSignal: "/icons/ios-wifi-signal.svg",
  kanbanSquare: "/icons/kanban-square.svg",
  layoutDashboard: "/icons/layout-dashboard.svg",
  layoutPanelLeft: "/icons/layout-panel-left.svg",
  loader: "/icons/loader.svg",
  logOut: "/icons/log-out.svg",
  logoMark: "/icons/logo-mark.svg",
  menu: "/icons/menu.svg",
  plus: "/icons/plus.svg",
  search: "/icons/search.svg",
  settings: "/icons/settings.svg",
  sortDesc: "/icons/sort-desc.svg",
  terminalSquare: "/icons/terminal-square.svg",
  thumbsUp: "/icons/thumbs-up.svg",
  user: "/icons/user.svg",
  xCircle: "/icons/x-circle.svg",
} as const;

export type IconName = keyof typeof iconPaths;
